### ISSUE TITLE
HWIPartiallySignedTransaction should contain a PartiallySignedTransaction, not a String

### ISSUE THREAD

**Issue by afilini** [bitcoindevkit/rust-hwi#3]
It would also be nice to implement `Deref<Target = PartiallySignedTransaction>` so that it can be used anywhere a `&PartiallySignedTransaction` is accepted.

**Comment by tanishq67** [comment]
Hi, thanks for raising the issue. 
Do you this will be fine?
![image](https://user-images.githubusercontent.com/52757132/154262358-775df01a-094f-4275-968b-49aaae589107.png)

**Comment by danielabrozzoni** [comment]
Closed by a49e78d50aa34a048ac2f2154e23c8baa2a7ae71
