### ISSUE TITLE
Bump rust-bitcoin to 0.29

### ISSUE THREAD

**Issue by danielabrozzoni** [bitcoindevkit/rust-hwi#50]
I had to revert https://github.com/bitcoindevkit/rust-hwi/commit/91b8e3c96786f0949a490737650afcd5c40f40ea for 0.2.3 (we needed the update in bdk, and bdk is still stuck at 0.28). Re-revert the commit for the next release.

**Comment by notmandatory** [comment]
@danielabrozzoni I think BDK is almost ready for this one now that rust-miniscript 0.8 is release with rust-bitcoin 0.29. Are you already working on a PR?

**Comment by danielabrozzoni** [comment]
I just have to re-apply https://github.com/bitcoindevkit/rust-hwi/commit/91b8e3c96786f0949a490737650afcd5c40f40ea :)
